version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: mcp-postgres-test
    environment:
      POSTGRES_DB: test_footfall
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_footfall"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data: